# Generated by Django 5.1.3 on 2025-09-03 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistaEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora_actuacion", models.TimeField()),
                ("rol", models.CharField(max_length=100)),
                (
                    "artista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.artista",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("fecha", models.DateTimeField()),
                ("lugar", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="eventos/"),
                ),
                ("edad_minima", models.IntegerField(default=18)),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("link_compra", models.URLField(blank=True, null=True)),
                (
                    "artistas",
                    models.ManyToManyField(
                        related_name="eventos",
                        through="eventos.ArtistaEvento",
                        to="booking.artista",
                    ),
                ),
            ],
        ),
    ]
