# Generated by Django 5.1.3 on 2026-01-12 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tienda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Objeto",
            fields=[
                (
                    "producto_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tienda.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objeto / Merch",
                "verbose_name_plural": "Objetos / Merch",
            },
            bases=("tienda.producto",),
        ),
        migrations.RemoveField(
            model_name="producto",
            name="modelos",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="tallas",
        ),
        migrations.CreateModel(
            name="Ropa",
            fields=[
                (
                    "producto_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tienda.producto",
                    ),
                ),
                (
                    "modelos",
                    models.ManyToManyField(
                        blank=True, related_name="prenda_ropa", to="tienda.modelo"
                    ),
                ),
                (
                    "tallas",
                    models.ManyToManyField(
                        blank=True, related_name="prenda_ropa", to="tienda.talla"
                    ),
                ),
            ],
            options={
                "verbose_name": "Prenda de Ropa",
                "verbose_name_plural": "Prendas de Ropa",
            },
            bases=("tienda.producto",),
        ),
    ]
