# Generated by Django 5.1.3 on 2026-01-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tienda", "0002_objeto_remove_producto_modelos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="archivo_digital",
            field=models.FileField(
                blank=True,
                help_text="Archivo para productos digitales (música, PDF, etc.)",
                null=True,
                upload_to="productos/digitales/",
                verbose_name="Archivo descargable",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="requires_shipping",
            field=models.BooleanField(
                default=True,
                help_text="Desmarcar para productos digitales que no necesitan envío físico",
                verbose_name="Requiere envío",
            ),
        ),
    ]
