# Generated by Django 5.1.3 on 2026-01-11 09:34

import django.db.models.deletion
import djangocms_text_ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardPluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("image", models.ImageField(upload_to="card_images/")),
                ("title", models.CharField(max_length=255)),
                ("description", djangocms_text_ckeditor.fields.HTMLField()),
                ("button_text", models.CharField(blank=True, max_length=50, null=True)),
                ("button_url", models.URLField(blank=True, null=True)),
                (
                    "alignment",
                    models.CharField(
                        choices=[
                            ("left", "Imagen Izquierda - Texto Derecha"),
                            ("right", "Imagen Derecha - Texto Izquierda"),
                        ],
                        default="left",
                        max_length=10,
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="HeroPluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("background_image", models.ImageField(upload_to="hero_images/")),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                ("button_text", models.CharField(blank=True, max_length=50, null=True)),
                ("button_url", models.URLField(blank=True, null=True)),
            ],
            bases=("cms.cmsplugin",),
        ),
    ]
