# Generated by Django 5.1.3 on 2026-01-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="heropluginmodel",
            name="logo_image",
            field=models.ImageField(
                blank=True,
                help_text="Sube un logo para mostrar en lugar del título de texto.",
                null=True,
                upload_to="hero_logos/",
            ),
        ),
        migrations.AlterField(
            model_name="heropluginmodel",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Texto del título (si no hay logo) o texto alternativo para el logo.",
                max_length=255,
                null=True,
            ),
        ),
    ]
