# Generated by Django 5.1.3 on 2026-01-11 10:06

import cms.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
        ("core", "0002_heropluginmodel_logo_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardpluginmodel",
            name="internal_page",
            field=cms.models.fields.PageField(
                blank=True,
                help_text="Si seleccionas una página, este enlace tendrá prioridad sobre la URL externa.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_plugin_link",
                to="cms.page",
                verbose_name="Página interna",
            ),
        ),
        migrations.AddField(
            model_name="heropluginmodel",
            name="internal_page",
            field=cms.models.fields.PageField(
                blank=True,
                help_text="Si seleccionas una página, este enlace tendrá prioridad sobre la URL externa.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hero_plugin_link",
                to="cms.page",
                verbose_name="Página interna",
            ),
        ),
        migrations.AlterField(
            model_name="cardpluginmodel",
            name="button_url",
            field=models.URLField(
                blank=True,
                help_text="Úsalo solo si no has seleccionado una página interna.",
                null=True,
                verbose_name="Enlace externo",
            ),
        ),
        migrations.AlterField(
            model_name="heropluginmodel",
            name="button_url",
            field=models.URLField(
                blank=True,
                help_text="Úsalo solo si no has seleccionado una página interna.",
                null=True,
                verbose_name="Enlace externo",
            ),
        ),
    ]
