# Generated by Django 5.1.3 on 2026-01-12 20:19

import cms.models.fields
import django.db.models.deletion
import djangocms_text_ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
        ("core", "0003_cardpluginmodel_internal_page_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventsGridPluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="Próximos Eventos", max_length=255
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        default=3, help_text="Número de eventos a mostrar."
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="ShopShowcasePluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="Novedades en la Tienda", max_length=255
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        default=4, help_text="Número de productos a mostrar."
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="CTAPluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "text",
                    djangocms_text_ckeditor.fields.HTMLField(
                        verbose_name="Texto Principal"
                    ),
                ),
                ("button_text", models.CharField(max_length=50)),
                (
                    "button_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Enlace externo"
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("dark", "Oscuro (Negro/Gris)"),
                            ("light", "Claro (Blanco/Gris)"),
                            ("brand", "Corporativo (Verde/Color Principal)"),
                        ],
                        default="dark",
                        max_length=20,
                    ),
                ),
                (
                    "internal_page",
                    cms.models.fields.PageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cta_plugin_link",
                        to="cms.page",
                        verbose_name="Página interna",
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
    ]
