# Generated by Django 5.1.3 on 2024-12-18 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_artista_fecha_inicio_artista_genero_musical_and_more"),
        ("musica", "0003_cancion_archivo_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cancion",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_lanzamiento", models.DateField()),
                (
                    "portada",
                    models.ImageField(
                        blank=True, null=True, upload_to="musica/portadas"
                    ),
                ),
                (
                    "artista_principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.artista",
                    ),
                ),
                (
                    "artistas_colaboradores",
                    models.ManyToManyField(
                        blank=True,
                        related_name="albumes_colaborativos",
                        to="booking.artista",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="musica.categoriamusical",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cancion",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="canciones",
                to="musica.album",
            ),
        ),
    ]
