# Generated by Django 5.1.3 on 2024-12-18 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("musica", "0004_alter_cancion_url_album_cancion_album"),
    ]

    operations = [
        migrations.RenameField(
            model_name="album",
            old_name="artistas_colaboradores",
            new_name="artistas",
        ),
        migrations.RemoveField(
            model_name="album",
            name="artista_principal",
        ),
    ]
