# Generated by Django 5.1.3 on 2024-12-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("musica", "0005_rename_artistas_colaboradores_album_artistas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancion",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
