# Generated by Django 5.1.3 on 2026-01-07 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carrito", "0002_initial"),
        ("tienda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(
                blank=True,
                help_text="Dirección de envío proporcionada por PayPal",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_producto", models.CharField(max_length=150)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "nombre_talla",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "nombre_modelo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tienda.modelo",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="carrito.order",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tienda.producto",
                    ),
                ),
                (
                    "talla",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tienda.talla",
                    ),
                ),
            ],
        ),
    ]
