# Generated by Django 5.1.3 on 2026-01-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carrito", "0003_order_shipping_address_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("PAYPAL", "PayPal"), ("STRIPE", "Stripe")],
                default="PAYPAL",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_payment_intent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
