# Generated by Django 5.1.3 on 2026-01-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carrito", "0004_order_payment_method_order_stripe_payment_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="requires_shipping",
            field=models.BooleanField(
                default=True,
                help_text="Se calcula automáticamente según los productos del carrito",
                verbose_name="Requiere envío",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="download_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Descargas realizadas"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="download_token",
            field=models.CharField(
                blank=True,
                help_text="Token único para descarga segura",
                max_length=64,
                null=True,
                verbose_name="Token de descarga",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="max_downloads",
            field=models.PositiveIntegerField(
                default=5, verbose_name="Máximo de descargas"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(
                blank=True, help_text="Dirección de envío", null=True
            ),
        ),
    ]
