# Generated by Django 5.1.3 on 2025-09-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("breve_descripcion", models.CharField(blank=True, max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("contacto", models.EmailField(blank=True, max_length=254)),
                ("redes_sociales", models.JSONField(blank=True, default=dict)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="booking/fotos/"
                    ),
                ),
                (
                    "genero_musical",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ubicacion", models.CharField(blank=True, max_length=200, null=True)),
                ("sitio_web", models.URLField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=15, null=True)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("visible", models.BooleanField(default=True)),
                (
                    "enlace_soundcloud",
                    models.URLField(
                        blank=True,
                        help_text="Enlace al perfil o track de SoundCloud del artista",
                        null=True,
                    ),
                ),
                (
                    "enlace_spotify",
                    models.URLField(
                        blank=True,
                        help_text="Enlace al perfil o track de Spotify del artista",
                        null=True,
                    ),
                ),
                (
                    "enlace_youtube",
                    models.URLField(
                        blank=True,
                        help_text="Enlace al canal o video de YouTube del artista",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_destino",
                    models.EmailField(default="contacto@lakultural.eu", max_length=254),
                ),
            ],
            options={
                "verbose_name": "Configuración de contacto",
                "verbose_name_plural": "Configuración de contacto",
            },
        ),
    ]
