# Generated by Django 5.1.3 on 2024-12-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_remove_artista_redes_sociales"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="fecha_inicio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="genero_musical",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="redes_sociales",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="artista",
            name="sitio_web",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="telefono",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="ubicacion",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
