# Generated by Django 5.1.3 on 2024-12-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_artista_fecha_inicio_artista_genero_musical_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artista",
            name="contacto",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="artista",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
    ]
