# Generated by Django 5.1.3 on 2024-12-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_alter_artista_contacto_alter_artista_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
