# Generated by Django 5.1.3 on 2024-12-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0006_artista_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="enlace_soundcloud",
            field=models.URLField(
                blank=True,
                help_text="Enlace al perfil o track de SoundCloud del artista",
                null=True,
            ),
        ),
    ]
