# Generated by Django 5.1.3 on 2024-12-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0007_artista_enlace_soundcloud"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="breve_descripcion",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="artista",
            name="enlace_spotify",
            field=models.URLField(
                blank=True,
                help_text="Enlace al perfil o track de Spotify del artista",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="artista",
            name="enlace_youtube",
            field=models.URLField(
                blank=True,
                help_text="Enlace al canal o video de YouTube del artista",
                null=True,
            ),
        ),
    ]
