# Generated by Django 5.1.3 on 2025-09-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Biografia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("contenido", models.TextField()),
                (
                    "imagenes",
                    models.ImageField(
                        blank=True, null=True, upload_to="biografia/fotos"
                    ),
                ),
                ("es_visible", models.BooleanField()),
            ],
        ),
    ]
